name: ci

on:
  push:
  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install flake8

      - name: Lint
        run: flake8 src --max-line-length=120 --ignore=E203,W503

      - name: Build Docker (no push)
        run: docker build -t mayo-demo-api -f Dockerfile .
